import rhinoscriptsyntax as rs

points = [[3.911825255740827, 14.6706769359003, 5.72234330941451],
 [-2.3637790761781385, 11.415734959235692, 7.544637556429262],
 [8.995515601393276, -0.6158559269194086, 25.173134555382667],
 [15.271119933312242, 2.639086049745199, 23.350840308367918],
 [1.52016841107547, 23.529743395412527, 13.309842013826755],
 [-4.755435920843496, 20.27480141874792, 15.132136260841506],
 [6.603858756727919, 8.243210532592817, 32.760633259794915],
 [12.879463088646885, 11.498152509257425, 30.938339012780162]]

created_points = []
for point in points:
    point_id = rs.AddPoint(point)
    created_points.append(point_id)
# for point in created_points:
rs.SelectObjects(created_points)