import rhinoscriptsyntax as rs

points = [[-3.1100875588534267, -1.1980551824170524, 19.662803464070667], [4.19496377770576, -6.991606296176263, 16.047420986034023], [0.8043159806804925, -0.908907669933092, -0.5509007646378592], [-6.500735355878694, 4.884643443826119, 3.0644817133987843], [-0.4844318366837384, 1.7688355092261419, 20.213704228708522], [6.820619499875448, -4.024715604533069, 16.59832175067188], [3.4299717028501804, 2.0579830217101023, -3.552713678800501e-15], [-3.8750796337090065, 7.851534135469313, 3.61538247803664]]

created_points = []
for point in points:
    point_id = rs.AddPoint(point)
    created_points.append(point_id)
# for point in created_points:
rs.SelectObjects(created_points)